services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: enterprise-sql-platform-lab-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ../datasets:/var/opt/mssql/import
    restart: "no"

volumes:
  sqlserver_data: